repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
# TODO: StyLua doesn't compile in pre-commit. Something to do with not finding `cc` compiler.
# Temporarily disabling the hook
# - repo: https://github.com/JohnnyMorganz/StyLua
#   rev: v2.2.0
#   hooks:
#   - id: stylua
